### ISSUE TITLE
Not able to access InheritableThreadLocal object from parent thread to hystrix thread pool

### ISSUE THREAD

**Issue by devratnaarya** [alibaba/transmittable-thread-local#139] opened 2019-05-08 13:06 UTC
I have InheritableThreadLocal<ConcurrentHashMap<String, Object>> thread that initializes when a request comes via the filter and set some transaction_id in it.

Now at the service layer, i'm calling 10 different API calls via CompletableFuture. All API service class have one execute method that is using RestTempate to make an API call. I put @HystrixCommand on execute method.

execute method is void type but it put the API response in InheritableThreadLocal object.

Now, `@HystrixCommand` is executed in saperate child thread and manage the thread pool.
when it reaches max no of pool size it starts re-using threads from the pool and at that time i didn't get the current state of InheritableThreadLocal object. it takes the old instance of the object that initialize when thread creates the first time.

for some demo code is posted here [Here](https://stackoverflow.com/questions/55862601/not-able-to-access-inheritablethreadlocal-object-from-parent-thread-in-fall-back)

**Comment by oldratlee** [comment] 2019-12-13 07:46
`Hystrix` problem is an specified usage of `TransmittableThreadLocal`.  and because

- We rarely use  `hystrix` 
- I'm not familiar with `hystrix`

so you need resolved the `hystrix` usage problem by yourself.

------------------

It seems that the problem is resolved in [the SOF question]((https://stackoverflow.com/questions/55862601/not-able-to-access-inheritablethreadlocal-object-from-parent-thread-in-fall-back)).

There are some resources about the problem and solution of `hystrix` and `TransmittableThreadLocal`(written by Chinese lang...):

- Spring Cloud中Hystrix 线程隔离导致ThreadLocal数据丢失
    - 上篇 http://cxytiandi.com/blog/detail/13331
    - 下篇 http://cxytiandi.com/blog/detail/18782
        包含了 解决方法 的 说明。

PS: similar issue about `hystrix` and `TransmittableThreadLocal`: https://github.com/alibaba/transmittable-thread-local/issues/153#issuecomment-552121666 , https://github.com/alibaba/transmittable-thread-local/issues/149#issuecomment-533793956 .

**Closed by oldratlee** 2019-12-13 07:46 UTC
